### ISSUE TITLE
Correct licence header

### ISSUE THREAD

**Issue by JohannesDaniel** [querqy/querqy-opensearch#10]
The project is not "Licensed to the Apache Software Foundation (ASF)" -> therefore the header must be changed

**Comment by ps48** [comment]
License Headers should be updated based on OpenSearch Plugin standards: https://github.com/opensearch-project/opensearch-plugins/blob/main/HEADERS.md

**Comment by ps48** [comment]
@JohannesDaniel I see all the files have ASF header. We can choose to not use OpenSearch Plugin standards' header as this code is owned by the Querqy community!

Please feel free to open the issue again, if you have some comments/need something changed.
