### ISSUE TITLE
[New Feature] Compatibility with OpenSearch version 2.3.0

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy-opensearch#22]
Create a Querqy plugin version for OpenSearch v2.3.0

- [ ] Update OpenSearch dependency
- [ ] Deal with rewriter configurations > 32k. ES v8.2  started constraining keyword field length to this limit due to an underlying Lucene constraint. We've handled this in querqy-elasticsearch by splitting the config string and make it a multi-valued field (https://github.com/querqy/querqy-elasticsearch/commit/f28482e876c90d0a43437f1704b85b253b6f8e08#diff-4df2f4a9444dba31b05fec9e95c89ece96ff12ce0c0f4806142232066b38055e and https://github.com/querqy/querqy-elasticsearch/commit/f28482e876c90d0a43437f1704b85b253b6f8e08#diff-32be4fd4b3f6e7fdd2bad5997fd60c60b5f3e2237c3855d4e7dd1d18b5d8602d ). The issue was revealed in this integration test: https://github.com/querqy/querqy-elasticsearch/blob/d1bece60a5779f89fcd2f2f860444614d1e1d58f/src/test/java/querqy/elasticsearch/RewriterIntegrationTest.java#L103

**Comment by ps48** [comment]
@renekrie I've created a PR #27  to handle rewriter configurations > 32k based on your changes in ES plugin. The OS plugin already had the integ test for `large query config`: [here](https://github.com/querqy/querqy-opensearch/blob/main/src/test/java/querqy/opensearch/RewriterIntegrationTest.java#L92). Do you know why was this not caught before?

**Comment by renekrie** [comment]
I think I wasn't precise enough in my description: ES introduced a check to prevent a potential issue in Lucene keyword fields. So the test triggered an exception in ES which we might not see in OS. It could be that there might just be an inconsistency at the Lucene level that we will not reveal with the test. Anyway, I thought that it would still be good to proactively deal with it. (I'll try to remember the place in ES where this was checked)
