### ISSUE TITLE
Add automated dependabot checks

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy-opensearch#24]
Compare https://github.com/querqy/querqy/blob/master/.github/dependabot.yml

**Comment by ps48** [comment]
@renekrie I see that Dependabot is enabled on this repo. Only admins of the repo can enable it. https://github.com/querqy/querqy-opensearch/network/updates

**Comment by renekrie** [comment]
Yes, I'll enable it as soon as the os2.0.0 release is out of the door in order to avoid any further delay

**Comment by ps48** [comment]
resolved in #26
